---

# -------------------------------------------------------------------------------------------------
# Job Name
# -------------------------------------------------------------------------------------------------
name: MYSQL-CI


# -------------------------------------------------------------------------------------------------
# When to run
# -------------------------------------------------------------------------------------------------
on:
  # Runs on Pull Requests
  pull_request:

  # Runs on master Branch and Tags
  push:
    branches:
      - master
    tags:
      - '[0-9]+.[0-9]+*'


# -------------------------------------------------------------------------------------------------
# What to run
# -------------------------------------------------------------------------------------------------
jobs:
  build:
    name: "[ MYSQL-${{ matrix.version }} ]"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        version:
          - 'mysql-5.5'
          - 'mysql-5.6'
          - 'mysql-5.7'
          - 'mysql-8.0'
          - 'mariadb-5.5'
          - 'mariadb-10.0'
          - 'mariadb-10.1'
          - 'mariadb-10.2'
          - 'mariadb-10.3'
          - 'mariadb-10.4'
          - 'mariadb-10.5'
          - 'percona-5.5'
          - 'percona-5.6'
          - 'percona-5.7'
          - 'percona-8.0'
    steps:

      # ------------------------------------------------------------
      # Checkout repository
      # ------------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v2

      # ------------------------------------------------------------
      # Build
      # ------------------------------------------------------------
      - name: Build
        run: |
          retry() {
            for n in $(seq ${RETRIES}); do
              echo "[${n}/${RETRIES}] ${*}";
              if eval "${*}"; then
                echo "[SUCC] ${n}/${RETRIES}";
                return 0;
              fi;
              sleep 2;
              echo "[FAIL] ${n}/${RETRIES}";
            done;
            return 1;
          }
          retry make build-${VERSION}
        env:
          VERSION: ${{ matrix.version }}
          RETRIES: 20

      # ------------------------------------------------------------
      # Test
      # ------------------------------------------------------------
      - name: Test
        run: |
          retry() {
            for n in $(seq ${RETRIES}); do
              echo "[${n}/${RETRIES}] ${*}";
              if eval "${*}"; then
                echo "[SUCC] ${n}/${RETRIES}";
                return 0;
              fi;
              sleep 2;
              echo "[FAIL] ${n}/${RETRIES}";
            done;
            return 1;
          }
          retry make test-${VERSION}
        env:
          VERSION: ${{ matrix.version }}
          RETRIES: 20
