---

# -------------------------------------------------------------------------------------------------
# Job Name
# -------------------------------------------------------------------------------------------------
name: params


# -------------------------------------------------------------------------------------------------
# Custom Variables
# -------------------------------------------------------------------------------------------------
env:
  NAME: MySQL
  MATRIX_VERSION: >-
    [
      {"NAME": "mysql",   "VERSION":  "5.5"},
      {"NAME": "mysql",   "VERSION":  "5.6"},
      {"NAME": "mysql",   "VERSION":  "5.7"},
      {"NAME": "mysql",   "VERSION":  "5.8"},
      {"NAME": "mariadb", "VERSION":  "5.5"},
      {"NAME": "mariadb", "VERSION": "10.0"},
      {"NAME": "mariadb", "VERSION": "10.1"},
      {"NAME": "mariadb", "VERSION": "10.2"},
      {"NAME": "mariadb", "VERSION": "10.3"},
      {"NAME": "mariadb", "VERSION": "10.4"},
      {"NAME": "mariadb", "VERSION": "10.5"},
      {"NAME": "mariadb", "VERSION": "10.6"},
      {"NAME": "mariadb", "VERSION": "10.0"},
      {"NAME": "percona", "VERSION":  "5.5"},
      {"NAME": "percona", "VERSION":  "5.6"},
      {"NAME": "percona", "VERSION":  "5.7"},
      {"NAME": "percona", "VERSION":  "8.0"}
    ]
  MATRIX_ARCH: >-
    [
      "linux/amd64",
      "linux/arm64"
    ]


# -------------------------------------------------------------------------------------------------
# When to run
# -------------------------------------------------------------------------------------------------
on:
  workflow_call:
    outputs:
      name:
        description: "The project name"
        value: ${{ jobs.params.outputs.name }}
      matrix_version:
        description: "The determined version matrix"
        value: ${{ jobs.params.outputs.matrix_version }}
      matrix_arch:
        description: "The determined architecture matrix"
        value: ${{ jobs.params.outputs.matrix_arch }}
      matrix_refs:
        description: "The determined git ref matrix (only during scheduled run)"
        value: ${{ jobs.params.outputs.matrix_refs }}

jobs:
  params:
    runs-on: ubuntu-latest

    outputs:
      name: ${{ steps.set-name.outputs.name }}
      matrix_version: ${{ steps.set-matrix-version.outputs.matrix }}
      matrix_arch: ${{ steps.set-matrix-arch.outputs.matrix }}
      matrix_refs: ${{ steps.set-matrix-refs.outputs.matrix }}

    steps:
      - name: Test JSON
        run: |
          jq -M -c \
            --argjson arches '${{ env.MATRIX_ARCH }}' \
            'map({NAME:.NAME, VERSION, ARCH:$arches[]})' <<<'${{ env.MATRIX_VERSION }}'

      - name: "Set Name"
        id: set-name
        run: |
          echo '::set-output name=name::${{ env.NAME }}'

      - name: "[Set-Output] Matrix 'Version'"
        id: set-matrix-version
        run: |
          echo "::set-output name=matrix::$( echo '${{ env.MATRIX_VERSION }}' | jq -M -c )"

      - name: "[Set-Output] Matrix 'Arch'"
        id: set-matrix-arch
        run: |
          echo "::set-output name=matrix::$( echo '${{ env.MATRIX_ARCH }}' | jq -M -c )"

      - name: "[Set-Output] Matrix 'Refs' (master branch and latest tag)"
        id: set-matrix-refs
        uses: cytopia/git-ref-matrix-action@v0.1.2
        with:
          repository_default_branch: master
          branches: master
          num_latest_tags: 1
        if: github.event_name == 'schedule'

      - name: "[DEBUG] Show settings'"
        run: |
          echo 'Name'
          echo '--------------------'
          echo '${{ steps.set-name.outputs.name }}'
          echo

          echo 'Matrix: Version'
          echo '--------------------'
          echo '${{ steps.set-matrix-version.outputs.matrix }}'
          echo

          echo 'Matrix: Arch'
          echo '--------------------'
          echo '${{ steps.set-matrix-arch.outputs.matrix }}'
          echo

          echo 'Matrix: Refs'
          echo '--------------------'
          echo '${{ steps.set-matrix-refs.outputs.matrix }}'
          echo
