---

# -------------------------------------------------------------------------------------------------
# Job Name
# -------------------------------------------------------------------------------------------------
name: params


# -------------------------------------------------------------------------------------------------
# Custom Variables
# -------------------------------------------------------------------------------------------------
env:
  NAME: MySQL
  MATRIX: >-
    [
      {
        "NAME":    "mysql",
        "VERSION": ["5.5", "5.6", "5.7"],
        "ARCH":    ["linux/amd64"]
      },
      {
        "NAME":    "mysql",
        "VERSION": ["8.0"],
        "ARCH":    ["linux/amd64", "linux/arm64"]
      },
      {
        "NAME":    "mariadb",
        "VERSION": ["5.5", "10.0"],
        "ARCH":    ["linux/amd64"]
      },
      {
        "NAME":    "mariadb",
        "VERSION": ["10.1", "10.2", "10.3", "10.4", "10.5", "10.6"],
        "ARCH":    ["linux/amd64", "linux/arm64"]
      },
      {
        "NAME":    "percona",
        "VERSION": ["5.5", "5.6", "5.7", "8.0"],
        "ARCH":    ["linux/amd64"]
      }
    ]


# -------------------------------------------------------------------------------------------------
# When to run
# -------------------------------------------------------------------------------------------------
on:
  workflow_call:
    outputs:
      name:
        description: "The project name"
        value: ${{ jobs.params.outputs.name }}
      matrix:
        description: "The determined version matrix"
        value: ${{ jobs.params.outputs.matrix }}
      refs:
        description: "The determined git ref matrix (only during scheduled run)"
        value: ${{ jobs.params.outputs.refs }}

jobs:
  params:
    runs-on: ubuntu-latest

    outputs:
      name: ${{ steps.set-name.outputs.name }}
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      refs: ${{ steps.set-refs.outputs.matrix }}

    steps:
      - name: "Set Name"
        id: set-name
        run: |
          echo '::set-output name=name::${{ env.NAME }}'

      - name: "[Set-Output] Matrix"
        id: set-matrix
        run: |
          echo "::set-output name=matrix::$( echo '${{ env.MATRIX }}' | jq -M -c )"

      - name: "[Set-Output] Matrix 'Refs' (master branch and latest tag)"
        id: set-refs
        uses: cytopia/git-ref-matrix-action@v0.1.3
        with:
          repository_default_branch: master
          branches: master
          num_latest_tags: 1
        if: github.event_name == 'schedule'

      - name: "[DEBUG] Show settings'"
        run: |
          echo 'Name'
          echo '--------------------'
          echo '${{ steps.set-name.outputs.name }}'
          echo

          echo 'Matrix'
          echo '--------------------'
          echo '${{ steps.set-matrix.outputs.matrix }}'
          echo

          echo 'Matrix: Refs'
          echo '--------------------'
          echo '${{ steps.set-matrix-refs.outputs.matrix }}'
          echo
